// ==================== CHATS ====================
window.cargarListaChats=async function(){
  await cargarTodosUsuarios();const div=document.getElementById('listaChats');if(!div)return;
  if(!userActual.matches?.length){div.innerHTML='<p>Aún no tienes matches.</p>';return;}
  const mo=[...userActual.matches].sort((a,b)=>{const af=chatsFijados.includes(a)?1:0;const bf=chatsFijados.includes(b)?1:0;if(af!==bf)return bf-af;const ma=userActual.chats?.[a]||[];const mb=userActual.chats?.[b]||[];const ua=ma[ma.length-1]?.fecha||'';const ub=mb[mb.length-1]?.fecha||'';return ub.localeCompare(ua);});
  div.innerHTML=mo.map(uid=>{const u=usuarios.find(x=>x.uid===uid);if(!u)return'';const msgs=userActual.chats?.[uid]||[];const ult=msgs[msgs.length-1];const prev=ult?(ult.texto==='__MATCH__'?'💖 ¡Son Match!':(ult.texto.startsWith('__REGALO__')?'🎁 Regalo':(ult.texto.startsWith('__ENCUESTA__')?'📊 Encuesta':(ult.texto.startsWith('__AUDIO__')?'🎤 Audio':(ult.texto.startsWith('__FOTO__')?'📷 Foto':ult.texto.substring(0,25)+'...'))))):'¡Empieza a chatear!';const h=ult?new Date(ult.fecha).toLocaleTimeString('es',{hour:'2-digit',minute:'2-digit'}):'';const f=u.foto?`style="background-image:url(${u.foto});background-size:cover;"`:`style="background:${obtenerColorAleatorio(getInicial(u.user))};"`;const cc=u.colorNombre?'nombre-'+u.colorNombre:'';const nl=chatsNoLeidos[uid]||0;const bh=nl>0?`<span class="chat-badge">${nl}</span>`:'';const ef=chatsFijados.includes(uid);let et='';if(u.conectado){et='🟢 En línea';}else if(u.ultimaDesconexion){const diff=Date.now()-new Date(u.ultimaDesconexion).getTime();const mins=Math.floor(diff/60000);const hrs=Math.floor(diff/3600000);if(mins<1)et='últ. vez ahora';else if(mins<60)et=`últ. vez hace ${mins}min`;else if(hrs<24)et=`últ. vez hace ${hrs}h`;else et=`últ. vez hace ${Math.floor(diff/86400000)}d`;}return`<div class="match-card${ef?' chat-fijado':''}" onclick="abrirChat('${uid}')"><div class="avatar avatar-sm" ${f}>${!u.foto?getInicial(u.user):''}<div class="${u.conectado?'punto-conexion':'punto-conexion punto-desconectado'}"></div></div><div class="chat-preview" style="flex:1;text-align:left;"><b class="${cc}">${u.user}${ef?' 📌':''}</b><small>${prev}</small>${et?`<small style="color:var(--text-secondary);font-size:10px;">${et}</small>`:''}</div>${bh}<div class="chat-hora">${h}</div></div>`;}).join('');feather.replace();};

window.abrirChat=async function(uid){
  clearInterval(intervaloContadorInvitacion);document.getElementById('invitacionJuego').classList.add('hidden');partidaActiva=null;
  await cargarTodosUsuarios();chatActivo=uid;window.chatActivo=chatActivo;chatsNoLeidos[uid]=0;userActual.chatsNoLeidos=chatsNoLeidos;await guardarTodo();actualizarBadgeChats();cargarListaChats();
  const u=usuarios.find(x=>x.uid===uid);if(!u)return;document.getElementById('chatCon').innerText=u.user;document.getElementById('chatCon').className=u.colorNombre?'nombre-'+u.colorNombre:'';const eo=estadosDisponibles.find(e=>e.id===u.estado)||estadosDisponibles[0];let et=u.conectado?eo.texto:'Desconectado';if(!u.conectado&&u.ultimaDesconexion){const diff=Date.now()-new Date(u.ultimaDesconexion).getTime();const mins=Math.floor(diff/60000);const hrs=Math.floor(diff/3600000);if(mins<1)et='últ. vez ahora';else if(mins<60)et=`últ. vez hace ${mins} min`;else if(hrs<24)et=`últ. vez hoy ${new Date(u.ultimaDesconexion).toLocaleTimeString('es',{hour:'2-digit',minute:'2-digit'})}`;else et=`últ. vez ${new Date(u.ultimaDesconexion).toLocaleDateString('es',{day:'numeric',month:'short'})}`;}document.getElementById('estadoChat').innerText=et;const bf=document.getElementById('btnFijarChat');if(bf)bf.innerText=chatsFijados.includes(uid)?'📌✅':'📌';const av=document.getElementById('avatarChat');av.innerHTML='';av.className='avatar avatar-sm'+(u.marco?' marco-'+u.marco:'');if(u.foto){av.style.backgroundImage=`url(${u.foto})`;av.style.backgroundSize='cover';av.innerText='';}else{av.style.background=obtenerColorAleatorio(getInicial(u.user));av.innerText=getInicial(u.user);av.style.color='white';}const punto=document.createElement('div');punto.className=u.conectado?'punto-conexion':'punto-conexion punto-desconectado';av.appendChild(punto);document.getElementById('listaChats').classList.add('hidden');document.getElementById('areaChat').classList.remove('hidden');document.getElementById('bottomNav').classList.add('hidden');document.getElementById('invitacionJuego').classList.add('hidden');document.getElementById('busquedaChatDiv').classList.add('hidden');document.getElementById('menuChatFlotante').classList.add('hidden');cargarMensajes();iniciarEscuchaChat(uid);feather.replace();};

window.toggleFijarChat=function(){if(!chatActivo)return;if(chatsFijados.includes(chatActivo)){chatsFijados=chatsFijados.filter(c=>c!==chatActivo);}else{if(chatsFijados.length>=3)return mostrarToast('Máximo 3 chats fijados','warning');chatsFijados.push(chatActivo);}userActual.chatsFijados=chatsFijados;guardarTodo();const bf=document.getElementById('btnFijarChat');if(bf)bf.innerText=chatsFijados.includes(chatActivo)?'📌✅':'📌';};
window.cerrarChat=function(){clearInterval(intervaloContadorInvitacion);document.getElementById('invitacionJuego').classList.add('hidden');partidaActiva=null;if(userActual){userActual.ultimaDesconexion=new Date().toISOString();guardarTodo();}document.getElementById('areaChat').classList.add('hidden');document.getElementById('listaChats').classList.remove('hidden');document.getElementById('bottomNav').classList.remove('hidden');chatActivo=null;window.chatActivo=null;};
window.confirmarAccion=function(){document.getElementById('modalConfirmacion').classList.add('hidden');if(accionPendiente)accionPendiente();accionPendiente=null;};
window.cancelarAccion=function(){document.getElementById('modalConfirmacion').classList.add('hidden');accionPendiente=null;};
window.notificarEscritura=function(){if(!chatActivo)return;clearTimeout(timeoutEscritura);setDoc(doc(db,"usuarios",userActual.uid),{escribiendo:true},{merge:true});timeoutEscritura=setTimeout(()=>{setDoc(doc(db,"usuarios",userActual.uid),{escribiendo:false},{merge:true});},2000);};

function iniciarEscuchaChat(uid){onSnapshot(doc(db,"usuarios",uid),async(snap)=>{const data=snap.data();if(!data)return;if(chatActivo!==uid){if(data.chats&&data.chats[userActual.uid]){const msgs=data.chats[userActual.uid];const misMsgs=userActual.chats?.[uid]||[];const nm=msgs.filter(m=>m.de!==userActual.user).length;const mmc=misMsgs.filter(m=>m.de!==userActual.user).length;if(nm>mmc){chatsNoLeidos[uid]=nm-mmc;userActual.chatsNoLeidos=chatsNoLeidos;actualizarBadgeChats();cargarListaChats();reaccionarMascota('mensaje');}}return;}const punto=document.querySelector('#avatarChat .punto-conexion');if(punto)data.conectado?punto.classList.remove('punto-desconectado'):punto.classList.add('punto-desconectado');const indicador=document.getElementById('indicadorEscribiendo');if(indicador){data.escribiendo?indicador.classList.remove('hidden'):indicador.classList.add('hidden');}await cargarTodosUsuarios();if(data.chats&&data.chats[userActual.uid]){if(!userActual.chats)userActual.chats={};userActual.chats[uid]=data.chats[userActual.uid];}cargarMensajes();});}

window.enviarFotoChat=async function(e){const f=e.target.files[0];if(!f||!chatActivo)return;if(!f.type.startsWith('image/'))return mostrarToast('Solo imágenes','warning');mostrarLoading();try{const sr=ref(storage,`usuarios/${userActual.uid}/chat/foto_${Date.now()}`);await uploadBytes(sr,f);const url=await getDownloadURL(sr);const nuevo={de:userActual.user,texto:`__FOTO__${url}`,fecha:new Date().toISOString()};if(!userActual.chats)userActual.chats={};if(!userActual.chats[chatActivo])userActual.chats[chatActivo]=[];userActual.chats[chatActivo].push(nuevo);cargarMensajes();const otro=usuarios.find(x=>x.uid===chatActivo);if(otro){if(!otro.chats)otro.chats={};if(!otro.chats[userActual.uid])otro.chats[userActual.uid]=[];otro.chats[userActual.uid].push(nuevo);await setDoc(doc(db,"usuarios",chatActivo),otro);}incrementarMision('chat');ganarXP(5);await guardarTodo();ocultarLoading();}catch(x){ocultarLoading();mostrarToast('Error al enviar foto','error');}e.target.value='';};

window.iniciarGrabacion=async function(){if(grabando)return detenerGrabacion();if(!navigator.mediaDevices)return mostrarToast('No soportado','error');try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});mediaRecorder=new MediaRecorder(stream);audioChunks=[];mediaRecorder.ondataavailable=(e)=>audioChunks.push(e.data);mediaRecorder.onstop=async()=>{const audioBlob=new Blob(audioChunks,{type:'audio/webm'});const sr=ref(storage,`usuarios/${userActual.uid}/chat/audio_${Date.now()}.webm`);await uploadBytes(sr,audioBlob);const url=await getDownloadURL(sr);const duracion=Math.round(audioChunks.length*0.1);const nuevo={de:userActual.user,texto:`__AUDIO__${JSON.stringify({url,duracion})}`,fecha:new Date().toISOString()};if(!userActual.chats)userActual.chats={};if(!userActual.chats[chatActivo])userActual.chats[chatActivo]=[];userActual.chats[chatActivo].push(nuevo);cargarMensajes();const otro=usuarios.find(x=>x.uid===chatActivo);if(otro){if(!otro.chats)otro.chats={};if(!otro.chats[userActual.uid])otro.chats[userActual.uid]=[];otro.chats[userActual.uid].push(nuevo);await setDoc(doc(db,"usuarios",chatActivo),otro);}incrementarMision('chat');ganarXP(5);await guardarTodo();const overlay=document.getElementById('grabacionOverlay');if(overlay)overlay.remove();document.getElementById('btnGrabar').innerText='🎤';grabando=false;};mediaRecorder.start();grabando=true;document.getElementById('btnGrabar').innerText='🔴';const overlay=document.createElement('div');overlay.id='grabacionOverlay';overlay.className='grabacion-overlay';overlay.innerHTML='🔴 Grabando... <button onclick="window.detenerGrabacion()" style="width:auto;min-height:auto;padding:4px 10px;background:white;color:var(--danger);border-radius:16px;font-size:11px;cursor:pointer;">Detener</button>';document.body.appendChild(overlay);}catch(err){mostrarToast('No se pudo acceder al micrófono','error');}};
window.detenerGrabacion=function(){if(mediaRecorder&&grabando){mediaRecorder.stop();}};

window.borrarMensaje=async function(index){if(!chatActivo)return;if(!confirm('¿Borrar este mensaje?'))return;if(!userActual.chats||!userActual.chats[chatActivo])return;userActual.chats[chatActivo].splice(index,1);const otro=usuarios.find(x=>x.uid===chatActivo);if(otro&&otro.chats&&otro.chats[userActual.uid]){otro.chats[userActual.uid].splice(index,1);await setDoc(doc(db,"usuarios",chatActivo),otro);}await guardarTodo();cargarMensajes();};
window.abrirBusqueda=function(){document.getElementById('busquedaChatDiv').classList.remove('hidden');document.getElementById('busquedaInput').value='';document.getElementById('busquedaInput').focus();resultadosBusqueda=[];indiceBusqueda=-1;};
window.cerrarBusqueda=function(){document.getElementById('busquedaChatDiv').classList.add('hidden');resultadosBusqueda=[];indiceBusqueda=-1;cargarMensajes();};
window.buscarEnChat=function(){const termino=document.getElementById('busquedaInput').value.trim().toLowerCase();if(!termino){resultadosBusqueda=[];indiceBusqueda=-1;cargarMensajes();return;}const msgs=userActual.chats?.[chatActivo]||[];resultadosBusqueda=[];msgs.forEach((m,i)=>{if(!m.texto.startsWith('__')&&m.texto.toLowerCase().includes(termino)){resultadosBusqueda.push({index:i,texto:m.texto});}});indiceBusqueda=resultadosBusqueda.length>0?0:-1;cargarMensajes();};
window.verStatsChat=function(){if(!chatActivo)return mostrarToast('Abre un chat primero','warning');const msgs=userActual.chats?.[chatActivo]||[];const mm=msgs.filter(m=>m.de===userActual.user&&!m.texto.startsWith('__'));const sm=msgs.filter(m=>m.de!==userActual.user&&!m.texto.startsWith('__'));const fotos=msgs.filter(m=>m.texto.startsWith('__FOTO__'));const audios=msgs.filter(m=>m.texto.startsWith('__AUDIO__'));const regalos=msgs.filter(m=>m.texto.startsWith('__REGALO__'));const encuestas=msgs.filter(m=>m.texto.startsWith('__ENCUESTA__'));const juegos=msgs.filter(m=>m.texto.startsWith('__INVITACION_JUEGO__')||m.texto.startsWith('__ESTADO_PARTIDA__'));const pm=msgs[0];const match=usuarios.find(x=>x.uid===chatActivo);const comp=calcularCompatibilidad(match);const div=document.getElementById('contenidoStatsChat');if(!div)return;div.innerHTML=`<div class="stat-item"><span>💬 Mensajes</span><span class="stat-valor">${mm.length+sm.length}</span></div><div class="stat-item"><span>📤 Tuyos</span><span>${mm.length}</span></div><div class="stat-item"><span>📥 De ${match?.user||'match'}</span><span>${sm.length}</span></div><div class="stat-item"><span>📷 Fotos</span><span>${fotos.length}</span></div><div class="stat-item"><span>🎤 Audios</span><span>${audios.length}</span></div><div class="stat-item"><span>🎁 Regalos</span><span>${regalos.length}</span></div><div class="stat-item"><span>📊 Encuestas</span><span>${encuestas.length}</span></div><div class="stat-item"><span>🎮 Juegos</span><span>${juegos.length}</span></div><div class="stat-item"><span>💖 Compatibilidad</span><span class="stat-valor">${comp}%</span></div><div class="stat-item"><span>📅 Primer mensaje</span><span>${pm?new Date(pm.fecha).toLocaleDateString('es'):'N/A'}</span></div>`;document.getElementById('modalStatsChat').classList.remove('hidden');};
window.cerrarModalStatsChat=function(){document.getElementById('modalStatsChat').classList.add('hidden');};
window.verGaleriaChat=function(){if(!chatActivo)return mostrarToast('Abre un chat primero','warning');const msgs=userActual.chats?.[chatActivo]||[];const fotos=msgs.filter(m=>m.texto.startsWith('__FOTO__')).map(m=>m.texto.replace('__FOTO__',''));const div=document.getElementById('contenidoGaleriaChat');if(!div)return;if(!fotos.length){div.innerHTML='<p style="text-align:center;padding:20px;">No hay fotos compartidas</p>';}else{div.innerHTML=fotos.map(f=>`<img src="${f}" onclick="abrirVisorFoto('${f}',false,0,'usuario')" style="width:100%;aspect-ratio:1;object-fit:cover;border-radius:6px;cursor:pointer;">`).join('');}document.getElementById('modalGaleriaChat').classList.remove('hidden');};
window.cerrarModalGaleriaChat=function(){document.getElementById('modalGaleriaChat').classList.add('hidden');};
window.crearEncuesta=function(){if(!chatActivo)return mostrarToast('Abre un chat primero','warning');document.getElementById('encuestaPregunta').value='';document.getElementById('encuestaOpc1').value='';document.getElementById('encuestaOpc2').value='';document.getElementById('encuestaOpc3').value='';document.getElementById('modalEncuesta').classList.remove('hidden');};
window.cerrarModalEncuesta=function(){document.getElementById('modalEncuesta').classList.add('hidden');};
window.enviarEncuesta=async function(){const p=document.getElementById('encuestaPregunta').value.trim();const o1=document.getElementById('encuestaOpc1').value.trim();const o2=document.getElementById('encuestaOpc2').value.trim();const o3=document.getElementById('encuestaOpc3').value.trim();if(!p||!o1||!o2)return mostrarToast('Pregunta y 2 opciones','warning');const opciones=[o1,o2];if(o3)opciones.push(o3);const eid=Date.now().toString(36)+Math.random().toString(36).substring(2,5);const ed={id:eid,pregunta:p,opciones,votos:{}};if(!userActual.encuestas)userActual.encuestas={};userActual.encuestas[eid]=ed;const nuevo={de:userActual.user,texto:`__ENCUESTA__${JSON.stringify(ed)}`,fecha:new Date().toISOString()};if(!userActual.chats)userActual.chats={};if(!userActual.chats[chatActivo])userActual.chats[chatActivo]=[];userActual.chats[chatActivo].push(nuevo);const otro=usuarios.find(x=>x.uid===chatActivo);if(otro){if(!otro.chats)otro.chats={};if(!otro.chats[userActual.uid])otro.chats[userActual.uid]=[];otro.chats[userActual.uid].push(nuevo);if(!otro.encuestas)otro.encuestas={};otro.encuestas[eid]=ed;await setDoc(doc(db,"usuarios",chatActivo),otro);}await guardarTodo();cerrarModalEncuesta();cargarMensajes();};
window.votarEncuesta=async function(eid,oi){if(!userActual.encuestas)userActual.encuestas={};if(!userActual.encuestas[eid]){const otro=usuarios.find(x=>x.uid===chatActivo);if(otro&&otro.encuestas&&otro.encuestas[eid]){userActual.encuestas[eid]=otro.encuestas[eid];}else return;}if(!userActual.encuestas[eid].votos)userActual.encuestas[eid].votos={};if(userActual.encuestas[eid].votos[userActual.uid]!==undefined)return mostrarToast('Ya votaste','warning');userActual.encuestas[eid].votos[userActual.uid]=oi;const otro=usuarios.find(x=>x.uid===chatActivo);if(otro){if(!otro.encuestas)otro.encuestas={};otro.encuestas[eid]=userActual.encuestas[eid];await setDoc(doc(db,"usuarios",chatActivo),otro);}await guardarTodo();cargarMensajes();};
window.enviarMsg=async function(){const msg=document.getElementById('msgInput').value.trim();if(!msg||!chatActivo)return;const nuevo={de:userActual.user,texto:msg,fecha:new Date().toISOString()};if(!userActual.chats)userActual.chats={};if(!userActual.chats[chatActivo])userActual.chats[chatActivo]=[];userActual.chats[chatActivo].push(nuevo);cargarMensajes();document.getElementById('msgInput').value='';await setDoc(doc(db,"usuarios",userActual.uid),{escribiendo:false},{merge:true});const otro=usuarios.find(x=>x.uid===chatActivo);if(otro){if(!otro.chats)otro.chats={};if(!otro.chats[userActual.uid])otro.chats[userActual.uid]=[];otro.chats[userActual.uid].push(nuevo);await setDoc(doc(db,"usuarios",chatActivo),otro);}incrementarMision('chat');ganarXP(5);await guardarTodo();cargarMensajes();};

window.cargarMensajes=function(){
  const md=document.getElementById('mensajesChat');if(!md)return;const msgs=userActual.chats?.[chatActivo]||[];const match=usuarios.find(x=>x.uid===chatActivo);
  md.innerHTML=msgs.map((m,index)=>{const h=new Date(m.fecha).toLocaleTimeString('es',{hour:'2-digit',minute:'2-digit'});const bb=(m.de===userActual.user&&!m.texto.startsWith('__'))?`<span class="msg-borrar" onclick="event.stopPropagation();window.borrarMensaje(${index})">✕</span>`:'';let tm=m.texto;if(resultadosBusqueda.length>0&&indiceBusqueda>=0&&!m.texto.startsWith('__')){const termino=document.getElementById('busquedaInput')?.value.trim().toLowerCase()||'';if(termino&&m.texto.toLowerCase().includes(termino)){const regex=new RegExp(`(${termino.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')})`,'gi');tm=m.texto.replace(regex,'<span class="resultado-busqueda">$1</span>');}}
    if(m.texto==='__MATCH__'){return`<div class="msg-match"><div class="avatar" style="background-image:url(${userActual.foto});background-size:cover;background-color:${obtenerColorAleatorio(getInicial(userActual.user))};">${!userActual.foto?getInicial(userActual.user):''}</div><span>💖 ¡Son Match!</span><div class="avatar" style="background-image:url(${match?.foto||''});background-size:cover;background-color:${obtenerColorAleatorio(getInicial(match?.user||'?'))};">${!match?.foto?getInicial(match?.user||'?'):''}</div></div>`;}
    if(m.texto.startsWith('__INVITACION_JUEGO__')||m.texto.startsWith('__ESTADO_PARTIDA__')){let d;try{d=JSON.parse(m.texto.replace('__INVITACION_JUEGO__','').replace('__ESTADO_PARTIDA__',''));}catch(e){d={juego:'desconocido'};}if(m.de!==userActual.user&&d.estado==='invitacion'){const tmsg=new Date(m.fecha).getTime();const tact=Date.now();const st=Math.floor((tact-tmsg)/1000);if(st<60){partidaActiva=d;document.getElementById('invitacionJuego').classList.remove('hidden');document.getElementById('textoInvitacion').innerText=`${m.de} te invita a jugar ${d.juego}`;let seg=60-st;document.getElementById('contadorInvitacion').innerText=`Tiempo restante: ${seg}s`;clearInterval(intervaloContadorInvitacion);intervaloContadorInvitacion=setInterval(()=>{seg--;document.getElementById('contadorInvitacion').innerText=`Tiempo restante: ${seg}s`;if(seg<=0){clearInterval(intervaloContadorInvitacion);document.getElementById('invitacionJuego').classList.add('hidden');partidaActiva=null;}},1000);}}return`<div class="msg-wa sistema">🎮 ${m.de===userActual.user?'Invitaste':'Te invitaron'} a jugar ${d.juego}<div class="msg-time">${h}</div></div>`;}
    if(m.texto.startsWith('__REVANCHA__')){let d;try{d=JSON.parse(m.texto.replace('__REVANCHA__',''));}catch(e){d={juego:'desconocido'};}if(m.de!==userActual.user){return`<div class="msg-wa sistema">🔄 ${m.de} quiere revancha en ${d.juego} <button onclick="window.aceptarRevancha(${JSON.stringify(d).replace(/"/g,'&quot;')})" style="width:auto;padding:3px 8px;font-size:11px;min-height:auto;background:var(--primary);color:white;border-radius:10px;margin-top:3px;">Aceptar</button><div class="msg-time">${h}</div></div>`;}return`<div class="msg-wa sistema">🔄 Pediste revancha en ${d.juego}<div class="msg-time">${h}</div></div>`;}
    if(m.texto.startsWith('💌')||m.texto.startsWith('⭐ SUPER LIKE'))return`<div class="msg-wa ${m.de===userActual.user?'enviado':'recibido'}" style="background:#fff3cd;color:#856404;">${tm}${bb}<div class="msg-time">${h}</div></div>`;
    if(m.texto.startsWith('__REGALO__')){let d;try{d=JSON.parse(m.texto.replace('__REGALO__',''));}catch(e){d={icono:'🎁',nombre:'Regalo',color:'#ff6b9d',animacion:'girar'};}return`<div class="msg-wa regalo" onclick="window.animarRegalo(this,'${d.animacion||'girar'}')" style="background:linear-gradient(135deg,${d.color||'#ff6b9d'},${d.color||'#ff6b9d'}88);color:white;text-align:center;align-self:center!important;margin:3px auto;"><div style="font-size:36px;">${d.icono||'🎁'}</div><b>${d.nombre||'Regalo'}</b> de ${m.de}<div class="msg-time" style="color:rgba(255,255,255,0.8);">${h}</div></div>`;}
    if(m.texto.startsWith('__FOTO__')){const url=m.texto.replace('__FOTO__','');return`<div class="msg-foto"><img src="${url}" onclick="abrirVisorFoto('${url}',false,0,'usuario')" loading="lazy"><span class="msg-time">${h}</span></div>`;}
    if(m.texto.startsWith('__AUDIO__')){let d;try{d=JSON.parse(m.texto.replace('__AUDIO__',''));}catch(e){d={url:'',duracion:0};}return`<div class="msg-wa ${m.de===userActual.user?'enviado':'recibido'} msg-audio"><button onclick="window.reproducirAudio(this,'${d.url}')">▶️</button><div class="audio-progreso"><div class="barra" style="width:0%"></div></div><span class="audio-duracion">${d.duracion||0}s</span>${bb}<div class="msg-time">${h}</div></div>`;}
    if(m.texto.startsWith('__ENCUESTA__')){let d;try{d=JSON.parse(m.texto.replace('__ENCUESTA__',''));}catch(e){d={id:'0',pregunta:'?',opciones:[],votos:{}};}const tv=Object.keys(d.votos||{}).length;const mv=(d.votos||{})[userActual.uid];return`<div class="msg-encuesta"><h4>📊 ${d.pregunta}</h4>${(d.opciones||[]).map((op,i)=>{const vo=Object.values(d.votos||{}).filter(v=>v===i).length;const pct=tv>0?Math.round((vo/tv)*100):0;return`<div class="opcion${mv===i?' votada':''}" onclick="window.votarEncuesta('${d.id}',${i})"><div class="barra-votos" style="width:${pct}%"></div><span class="texto-opcion">${op} ${tv>0?`(${vo})`:''}</span></div>`;}).join('')}<div class="total-votos">${tv} voto${tv!==1?'s':''}</div><div class="msg-time">${h}</div></div>`;}
    if(m.texto.startsWith('🎮'))return`<div class="msg-wa sistema">${tm}<div class="msg-time">${h}</div></div>`;
    return`<div class="msg-wa ${m.de===userActual.user?'enviado':'recibido'}">${tm}${bb}<div class="msg-time">${h}</div></div>`;
  }).join('');const box=document.getElementById('chatBoxWa');if(box)box.scrollTop=box.scrollHeight;
};

window.reproducirAudio=function(btn,url){const audio=new Audio(url);const barra=btn.parentElement.querySelector('.barra');btn.innerText='⏸️';audio.play();audio.ontimeupdate=()=>{const pct=(audio.currentTime/audio.duration)*100;if(barra)barra.style.width=pct+'%';};audio.onended=()=>{btn.innerText='▶️';if(barra)barra.style.width='0%';};};
window.animarRegalo=function(el,animacion){el.classList.add('abierto');setTimeout(()=>el.classList.remove('abierto'),800);const ef=document.createElement('span');ef.innerText='✨';ef.style.cssText='position:fixed;pointer-events:none;z-index:300;animation:flotarCorazon 1.2s ease-out forwards;font-size:28px;';ef.style.left=el.getBoundingClientRect().left+'px';ef.style.top=el.getBoundingClientRect().top+'px';document.body.appendChild(ef);setTimeout(()=>ef.remove(),1500);};
