// ==================== JUEGOS LOCALES ====================
window.cerrarJuegoLocal=function(){document.getElementById('juegoLocalCompleto').classList.add('hidden');document.getElementById('bottomNav').classList.remove('hidden');document.getElementById('mainContainer').style.paddingBottom='80px';mostrar('juegos');};
window.confirmarSalirJuego=function(){document.getElementById('textoConfirmacion').innerText='¿Seguro que quieres salir? Perderás el progreso.';accionPendiente=()=>cerrarJuegoLocal();document.getElementById('modalConfirmacion').classList.remove('hidden');};
function abrirJuegoLocal(htmlContenido){document.getElementById('contenidoJuegoLocal').innerHTML=htmlContenido;document.getElementById('juegoLocalCompleto').classList.remove('hidden');document.getElementById('bottomNav').classList.add('hidden');document.getElementById('mainContainer').style.paddingBottom='0';}
function mostrarResultadoJuego(mensaje,tipoJuego){const dm=document.getElementById('mensajeJuegoLocal');if(dm){dm.innerHTML=`<p style="font-size:16px;font-weight:bold;margin:12px 0;">${mensaje}</p><button onclick="jugarDeNuevo('${tipoJuego}')" style="margin:4px;padding:8px 16px;" class="btn-primario">Jugar de nuevo</button><button class="btn-sec" onclick="cerrarJuegoLocal()" style="margin:4px;padding:8px 16px;">Volver</button>`;}}
window.jugarDeNuevo=function(tipo){if(tipo==='gato')window.jugarGato();else if(tipo==='adivina')window.jugarAdivina();else if(tipo==='ahorcado')window.jugarAhorcado();else if(tipo==='memoria')window.jugarMemoria();};

// GATO
let tableroGato=Array(9).fill('');let turnoGato='X';let juegoActivo=false;
window.jugarGato=function(){tableroGato=Array(9).fill('');turnoGato='X';juegoActivo=true;abrirJuegoLocal(`<h3 id="turnoGato">Tu turno: X</h3><div class="tablero-gato" id="tableroGato"></div><div id="mensajeJuegoLocal"></div>`);pintarGato();};
function pintarGato(){const div=document.getElementById('tableroGato');if(!div)return;div.innerHTML='';tableroGato.forEach((v,i)=>{const celda=document.createElement('div');celda.style.cssText='width:75px;height:75px;background:var(--card-bg);border:1px solid var(--border);border-radius:8px;display:flex;align-items:center;justify-content:center;font-size:32px;cursor:pointer;color:var(--text);';celda.innerText=v;celda.onclick=()=>jugarTurno(i);div.appendChild(celda);});}
function jugarTurno(i){if(!juegoActivo||tableroGato[i]!==''||turnoGato!=='X')return;tableroGato[i]='X';pintarGato();if(revisarGanador('X'))return terminarJuego('X');if(tableroGato.every(c=>c!==''))return terminarJuego('empate');turnoGato='O';document.getElementById('turnoGato').innerText='Turno PC: O';setTimeout(()=>{const mp=mejorMovimiento();tableroGato[mp]='O';pintarGato();if(revisarGanador('O'))return terminarJuego('O');if(tableroGato.every(c=>c!==''))return terminarJuego('empate');turnoGato='X';document.getElementById('turnoGato').innerText='Tu turno: X';},500);}
function mejorMovimiento(){for(let i=0;i<9;i++)if(tableroGato[i]===''){tableroGato[i]='O';if(revisarGanador('O')){tableroGato[i]='';return i;}tableroGato[i]='';}for(let i=0;i<9;i++)if(tableroGato[i]===''){tableroGato[i]='X';if(revisarGanador('X')){tableroGato[i]='';return i;}tableroGato[i]='';}if(tableroGato[4]==='')return 4;const esq=[0,2,6,8].filter(i=>tableroGato[i]==='');if(esq.length)return esq[Math.floor(Math.random()*esq.length)];const lad=[1,3,5,7].filter(i=>tableroGato[i]==='');return lad[Math.floor(Math.random()*lad.length)];}
function revisarGanador(j){const w=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];return w.some(c=>c.every(i=>tableroGato[i]===j));}
async function terminarJuego(r){juegoActivo=false;let m='';if(r==='X'){userActual.puntos+=15;await verificarInsignia('gato');actualizarRachaVictorias('gato',true);m='🎉 ¡Ganaste Gato! +15pts';}else if(r==='O'){actualizarRachaVictorias('gato',false);m='😢 Perdiste';}else m='😐 Empate';incrementarMision('gato');ganarXP(10);await guardarTodo();actualizarUI();mostrarResultadoJuego(m,'gato');}

// ADIVINA
let numeroSecreto=0;let intentosRestantes=8;
window.jugarAdivina=function(){numeroSecreto=Math.floor(Math.random()*100)+1;intentosRestantes=8;abrirJuegoLocal(`<h3>Adivina el Número</h3><p>Tienes 8 intentos</p><p style="font-size:16px;" id="pistaAdivina">Escribe un número</p><p>Intentos: <span id="intentosAdivina">8</span>/8</p><input id="inputAdivina" type="number" placeholder="Tu número"><button id="btnProbarAdivina" onclick="probarNumero()" class="btn-primario">Probar</button><div id="mensajeJuegoLocal"></div>`);};
window.probarNumero=async function(){const btn=document.getElementById('btnProbarAdivina'),input=document.getElementById('inputAdivina');if(!btn||intentosRestantes<=0)return;const num=parseInt(input.value);if(!num||num<1||num>100)return mostrarToast('Pon un número del 1 al 100','warning');intentosRestantes--;document.getElementById('intentosAdivina').innerText=intentosRestantes;if(num===numeroSecreto){userActual.puntos+=20;await verificarInsignia('adivina');actualizarRachaVictorias('adivina',true);btn.disabled=true;incrementarMision('adivina');ganarXP(15);await guardarTodo();actualizarUI();mostrarResultadoJuego('🎉 ¡Acertaste! +20pts','adivina');return;}else if(intentosRestantes<=0){actualizarRachaVictorias('adivina',false);btn.disabled=true;incrementarMision('adivina');mostrarResultadoJuego(`😢 Era ${numeroSecreto}`,'adivina');return;}else{document.getElementById('pistaAdivina').innerText=num<numeroSecreto?'Es MAYOR ⬆️':'Es MENOR ⬇️';input.value='';}};

// AHORCADO (GRID 3x9)
const palabras=['MANGO','GATO','PERRO','CASA','LIBRO','MUSICA','CHILE','JUEGO','AMIGOS','RANKING','PLAYA','MONTAÑA','CIELO','FUEGO','AGUA'];
let palabraSecreta='';let letrasAdivinadas=[];let intentosAhorcado=6;
window.jugarAhorcado=function(){palabraSecreta=palabras[Math.floor(Math.random()*palabras.length)];letrasAdivinadas=[];intentosAhorcado=6;abrirJuegoLocal(`<h3>Ahorcado - 6 Intentos</h3><p>Intentos: <span id="intentosAhorcado">6</span>/6</p><div id="palabraAhorcado" style="font-size:26px;letter-spacing:6px;margin:16px 0;"></div><p>Letras:</p><div id="letrasUsadas" style="margin:8px 0;"></div><div id="mensajeJuegoLocal"></div>`);actualizarAhorcado();};
function actualizarAhorcado(){document.getElementById('intentosAhorcado').innerText=intentosAhorcado;document.getElementById('palabraAhorcado').innerText=palabraSecreta.split('').map(l=>letrasAdivinadas.includes(l)?l:'_').join(' ');const abc='ABCDEFGHIJKLMNOPQRSTUVWXYZ';document.getElementById('letrasUsadas').innerHTML=`<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:3px;max-width:280px;margin:0 auto;">${abc.split('').map(l=>{const u=letrasAdivinadas.includes(l);return`<button class="letra-btn" ${u?'disabled':''} onclick="probarLetraBtn('${l}')" style="padding:6px 3px;min-height:32px;font-size:15px;font-weight:700;${u?'opacity:0.3;background:var(--btn-bg);':'background:var(--card-bg);border:1px solid var(--border);border-radius:5px;cursor:pointer;'}">${l}</button>`;}).join('')}</div>`;}
window.probarLetraBtn=async function(l){if(letrasAdivinadas.includes(l)||intentosAhorcado<=0)return;letrasAdivinadas.push(l);if(!palabraSecreta.includes(l))intentosAhorcado--;const pm=palabraSecreta.split('').map(x=>letrasAdivinadas.includes(x)?x:'_').join('');if(!pm.includes('_')){userActual.puntos+=25;await verificarInsignia('ahorcado');actualizarRachaVictorias('ahorcado',true);incrementarMision('ahorcado');ganarXP(20);await guardarTodo();actualizarUI();mostrarResultadoJuego('🎉 ¡Ganaste! +25pts','ahorcado');return;}if(intentosAhorcado<=0){actualizarRachaVictorias('ahorcado',false);incrementarMision('ahorcado');mostrarResultadoJuego(`😢 Era ${palabraSecreta}`,'ahorcado');return;}actualizarAhorcado();};

// MEMORIA
let cartasMemoria=[];let cartaSeleccionada=null;let paresEncontrados=0;
window.jugarMemoria=function(){const emojis=['🍎','🍌','🍇','🍓','🍊','🍒'];cartasMemoria=[...emojis.slice(0,4),...emojis.slice(0,4)].sort(()=>Math.random()-0.5);paresEncontrados=0;cartaSeleccionada=null;abrirJuegoLocal(`<h3>Memoria</h3><p>Pares: <span id="paresMemoria">0</span>/4</p><div class="tablero-memoria" id="tableroMemoria"></div><div id="mensajeJuegoLocal"></div>`);pintarMemoria();};
function pintarMemoria(){document.getElementById('paresMemoria').innerText=paresEncontrados;const div=document.getElementById('tableroMemoria');div.innerHTML='';cartasMemoria.forEach((emoji,i)=>{const carta=document.createElement('div');carta.style.cssText='width:55px;height:55px;background:var(--card-bg);border:1px solid var(--border);border-radius:8px;display:flex;align-items:center;justify-content:center;font-size:26px;cursor:pointer;';carta.innerText='?';carta.onclick=()=>voltearCarta(i,emoji,carta);div.appendChild(carta);});}
async function voltearCarta(i,emoji,elemento){if(elemento.innerText!=='?'||cartaSeleccionada===i)return;elemento.innerText=emoji;if(cartaSeleccionada===null){cartaSeleccionada={i,emoji,elemento};}else{if(cartaSeleccionada.emoji===emoji){paresEncontrados++;cartaSeleccionada=null;if(paresEncontrados===4){userActual.puntos+=20;await verificarInsignia('memoria');actualizarRachaVictorias('memoria',true);incrementarMision('memoria');ganarXP(15);await guardarTodo();actualizarUI();mostrarResultadoJuego('🎉 ¡Ganaste! +20pts','memoria');return;}}else{setTimeout(()=>{elemento.innerText='?';cartaSeleccionada.elemento.innerText='?';cartaSeleccionada=null;},600);}}}

// RANKING TOP 5
window.cargarRankingTop = async function() {
  try {
    const q = query(collection(db,"usuarios"), orderBy("puntos","desc"), limit(5));
    const snap = await getDocs(q); const todos = snap.docs.map(d => d.data());
    let html = '';
    todos.forEach((u, i) => {
      const clase = i===0?'ranking-1':i===1?'ranking-2':i===2?'ranking-3':'';
      const bg = u.foto ? `background-image:url(${u.foto});background-size:cover;` : `background:${obtenerColorAleatorio(getInicial(u.user))};`;
      const ini = !u.foto ? getInicial(u.user) : '';
      const cc = u.colorNombre ? ' nombre-'+u.colorNombre : '';
      const esYo = u.uid === userActual?.uid;
      const mc = u.marco ? ' marco-'+u.marco : '';
      html += `<div class="ranking-item ${clase} ${esYo?'ranking-yo':''}"><span class="ranking-numero">#${i+1}</span><div class="ranking-foto ${mc.trim()}" style="${bg}">${ini}</div><span class="ranking-nombre${cc}">${u.user}${esYo?' <span class="ranking-tu">(Tú)</span>':''}</span><span class="ranking-puntos">${u.puntos||0} pts</span></div>`;
    });
    const el = document.getElementById('listaRankingTop'); if(el) el.innerHTML = html || '<p style="text-align:center;">No hay ranking aún</p>';
    feather.replace();
  } catch(err) { const el = document.getElementById('listaRankingTop'); if(el) el.innerHTML = '<p style="text-align:center;">Cargando ranking...</p>'; }
};

async function verificarInsignia(juego){if(!userActual.insignias)userActual.insignias=[];const ni={gato:'🐱 Maestro del Gato',adivina:'🔢 Adivinador',ahorcado:'💀 Ahorcado',memoria:'🧠 Memorión',ppt:'✊ PPT'};const ins=ni[juego];if(ins&&!userActual.insignias.includes(ins)){userActual.insignias.push(ins);await guardarTodo();mostrarToast(`🏅 ¡Nueva insignia: ${ins}!`,'success');actualizarInsignias();}}

// MISIONES DIARIAS (ORDENADAS)
window.incrementarMision=function(tipo){if(!userActual?.misiones)return;for(let id in userActual.misiones){const m=userActual.misiones[id];const def=misionesDiarias.find(d=>d.id===id);if(def?.juego===tipo&&m.progreso<m.meta)m.progreso++;}guardarTodo();cargarMisiones();};
window.cargarMisiones=function(){if(!userActual)return;if(!userActual.misiones)userActual.misiones={};const fh=new Date().toDateString();if(userActual.ultimaMision!==fh){const sel=misionesDiarias.sort(()=>Math.random()-0.5).slice(0,4);userActual.misiones={};sel.forEach(m=>userActual.misiones[m.id]={progreso:0,meta:m.meta,puntos:m.puntos,texto:m.texto});userActual.ultimaMision=fh;guardarTodo();}const div=document.getElementById('misionesDia');if(!div)return;let html='<h3>📋 Misiones de hoy</h3>';const mk=Object.keys(userActual.misiones);const comp=mk.filter(k=>userActual.misiones[k].progreso>=userActual.misiones[k].meta);const pend=mk.filter(k=>userActual.misiones[k].progreso<userActual.misiones[k].meta);const ord=[...comp,...pend];ord.forEach(k=>{const d=userActual.misiones[k];const c=d.progreso>=d.meta;if(c){html+=`<div class="mision-item mision-completada"><span>✅ ${d.texto} (${d.progreso}/${d.meta})</span><button onclick="completarMision('${k}')" style="width:auto;padding:3px 8px;font-size:11px;min-height:auto;" class="btn-aceptar">+${d.puntos}</button></div>`;}else{html+=`<div class="mision-item"><span>${d.texto} (${d.progreso}/${d.meta})</span><small style="color:var(--text-secondary);">En progreso</small></div>`;}});if(!ord.length)html+='<p style="text-align:center;color:var(--success);">¡Todas completadas!</p>';div.innerHTML=html;feather.replace();};
window.completarMision=async function(mid){if(!userActual?.misiones?.[mid])return;const m=userActual.misiones[mid];if(m.progreso<m.meta)return;userActual.puntos+=m.puntos;delete userActual.misiones[mid];await guardarTodo();actualizarUI();cargarMisiones();mostrarToast(`¡Misión completada! +${m.puntos} pts`,'success');};
